 1. Importar
 2. Normalizar ()
 3. Dividir : Data entrenamiento vs Data Testeo
 4. Entrenar
 5. Aplicar

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('Data/heart.csv')
data.head(3)     

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   

   ca  thal  class  
0   0     1      1  
1   0     2      1  
2   0     2      1

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  class     303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [79]:
# Correlacion
data.corr()

age       sex        cp  trestbps      chol       fbs  \
age       1.000000 -0.098447 -0.068653  0.279351  0.213678  0.121308   
sex      -0.098447  1.000000 -0.049353 -0.056769 -0.197912  0.045032   
cp       -0.068653 -0.049353  1.000000  0.047608 -0.076904  0.094444   
trestbps  0.279351 -0.056769  0.047608  1.000000  0.123174  0.177531   
chol      0.213678 -0.197912 -0.076904  0.123174  1.000000  0.013294   
fbs       0.121308  0.045032  0.094444  0.177531  0.013294  1.000000   
restecg  -0.116211 -0.058196  0.044421 -0.114103 -0.151040 -0.084189   
thalach  -0.398522 -0.044020  0.295762 -0.046698 -0.009940 -0.008567   
exang     0.096801  0.141664 -0.394280  0.067616  0.067023  0.025665   
oldpeak   0.210013  0.096093 -0.149230  0.193216  0.053952  0.005747   
slope    -0.168814 -0.030711  0.119717 -0.121475 -0.004038 -0.059894   
ca        0.276326  0.118261 -0.181053  0.101389  0.070511  0.137979   
thal      0.068001  0.210041 -0.161736  0.062210  0.098803 -0.032019   
class    -0.225439 -0.280937  0.433798 -0.144931 -0.085239 -0.028046   

           restecg   thalach     exang   oldpeak     slope        ca  \
age      -0.116211 -0.398522  0.096801  0.210013 -0.168814  0.276326   
sex      -0.058196 -0.044020  0.141664  0.096093 -0.030711  0.118261   
cp        0.044421  0.295762 -0.394280 -0.149230  0.119717 -0.181053   
trestbps -0.114103 -0.046698  0.067616  0.193216 -0.121475  0.101389   
chol     -0.151040 -0.009940  0.067023  0.053952 -0.004038  0.070511   
fbs      -0.084189 -0.008567  0.025665  0.005747 -0.059894  0.137979   
restecg   1.000000  0.044123 -0.070733 -0.058770  0.093045 -0.072042   
thalach   0.044123  1.000000 -0.378812 -0.344187  0.386784 -0.213177   
exang    -0.070733 -0.378812  1.000000  0.288223 -0.257748  0.115739   
oldpeak  -0.058770 -0.344187  0.288223  1.000000 -0.577537  0.222682   
slope     0.093045  0.386784 -0.257748 -0.577537  1.000000 -0.080155   
ca       -0.072042 -0.213177  0.115739  0.222682 -0.080155  1.000000   
thal     -0.011981 -0.096439  0.206754  0.210244 -0.104764  0.151832   
class     0.137230  0.421741 -0.436757 -0.430696  0.345877 -0.391724   

              thal     class  
age       0.068001 -0.225439  
sex       0.210041 -0.280937  
cp       -0.161736  0.433798  
trestbps  0.062210 -0.144931  
chol      0.098803 -0.085239  
fbs      -0.032019 -0.028046  
restecg  -0.011981  0.137230  
thalach  -0.096439  0.421741  
exang     0.206754 -0.436757  
oldpeak   0.210244 -0.430696  
slope    -0.104764  0.345877  
ca        0.151832 -0.391724  
thal      1.000000 -0.344029  
class    -0.344029  1.000000

# Normalizar

### Extraer variable dependiente

In [5]:
variable_dependiente = data['class']
variable_dependiente.head(3)

0    1
1    1
2    1
Name: class, dtype: int64

### Extraer variable independiente

In [7]:
variable_independiente = data.drop('class',axis=1)
variable_independiente.head(3)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2

In [8]:
# librería para reescalar poner los valores entre 0 y 1
from sklearn.preprocessing import StandardScaler

In [9]:
variable_independiente_normalizada = StandardScaler().fit_transform(variable_independiente)

# Buscar ecuación de normalización 
# https://economipedia.com/definiciones/normalizacion-estadistica.html

In [10]:
variable_independiente_normalizada
# ya no será un dataFrame, sino un array, por eso no puedo usar .head()

array([[ 0.9521966 ,  0.68100522,  1.97312292, ..., -2.27457861,
        -0.71442887, -2.14887271],
       [-1.91531289,  0.68100522,  1.00257707, ..., -2.27457861,
        -0.71442887, -0.51292188],
       [-1.47415758, -1.46841752,  0.03203122, ...,  0.97635214,
        -0.71442887, -0.51292188],
       ...,
       [ 1.50364073,  0.68100522, -0.93851463, ..., -0.64911323,
         1.24459328,  1.12302895],
       [ 0.29046364,  0.68100522, -0.93851463, ..., -0.64911323,
         0.26508221,  1.12302895],
       [ 0.29046364, -1.46841752,  0.03203122, ..., -0.64911323,
         0.26508221, -0.51292188]])

### Ejecutar la separación de la data de entrenamiento y testeo

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
# test_size=0.25 : el 25% será data de testeo y resto será data de entrenamiento
# shuffle=True : la separación de la data de entrenamiento y testeo será aleatorio
# random_state = 125 # AVERIGUAR que DATO PONER AQUI, AUN ESTOY EN DUDA !!!!
# random_state : en un stackoverflow recomendaro que en produccion esa variable quitarla para que la separacion de data sea random, y no fija

x_train,x_test,y_train,y_test = train_test_split(variable_independiente_normalizada,variable_dependiente,test_size=0.25, shuffle=True, random_state=125)

# 4. Entrenar el algoritmo con la data de entrenamiento

In [18]:
# subir la libreria de random forest
# RandomForestClassifier => para esto
from sklearn.ensemble import RandomForestClassifier

### Construir el modelo

In [30]:
rf = RandomForestClassifier(max_depth=4,n_estimators=100)
#rf = modelo construido

#max_dep=4 : numero de ramas será 4
#n_estimators=100 : número árboles será 100

# 5. Aplicar a la data de Testeo

In [46]:
rf.fit(x_train,y_train) # entrenar (construyo los árboles en base a la data de entrenamiento)

RandomForestClassifier(max_depth=4)

In [47]:
rf.score(x_test,y_test) # precisión

0.8026315789473685

# 6. Aplicación

In [63]:
x_test.shape #veo dimension

(76, 13)

In [75]:
x_test[4]

array([-0.37126932,  0.68100522,  1.97312292, -0.3783023 , -0.64284335,
       -0.41763453, -1.00583187, -1.07781984,  1.43548113,  0.31091206,
        0.97635214,  0.26508221, -0.51292188])

In [76]:
x_test[4].shape

(13,)

In [77]:
x_test[4].reshape(1,13) #invierte la dimension ... de 13,1 a 1,13

array([[-0.37126932,  0.68100522,  1.97312292, -0.3783023 , -0.64284335,
        -0.41763453, -1.00583187, -1.07781984,  1.43548113,  0.31091206,
         0.97635214,  0.26508221, -0.51292188]])

In [92]:
rf.predict(x_test[4].reshape(1,13))
# reshape : Reacomodar la dimension cuando se predice solo 1

array([1], dtype=int64)

# 7. Miscelaneo

In [78]:
## OTRAS CONSULTAS

In [73]:
# observo el peso de cada variable (su importancia para todo el bósque)
rf.feature_importances_

array([0.0401884 , 0.03412167, 0.14942366, 0.03702108, 0.03200406,
       0.00173285, 0.00917577, 0.12107786, 0.0952508 , 0.11838308,
       0.06874963, 0.16625667, 0.12661448])

# 8. Elegir mejor parametrización: Ejecutando con diferentes parámetros

In [91]:
profundidad_list = [2,4,10,15]
estimador_list =[10,50,100,500]

for profundidad in profundidad_list:
    for estimador in estimador_list:
        print(f'_____ arboles:{estimador} depth:{profundidad} ______')
        for i in range(1,4):
            randomeForest = RandomForestClassifier(max_depth=profundidad,n_estimators=estimador)
            randomeForest.fit(x_train,y_train)
            prediccion= randomeForest.score(x_test,y_test)
            print(f'%:{prediccion}')

_____ arboles:10 depth:2 ______
%:0.7894736842105263
%:0.7763157894736842
%:0.75
_____ arboles:50 depth:2 ______
%:0.7631578947368421
%:0.7631578947368421
%:0.7763157894736842
_____ arboles:100 depth:2 ______
%:0.7763157894736842
%:0.7631578947368421
%:0.8157894736842105
_____ arboles:500 depth:2 ______
%:0.8026315789473685
%:0.7894736842105263
%:0.7894736842105263
_____ arboles:10 depth:4 ______
%:0.7236842105263158
%:0.7763157894736842
%:0.8157894736842105
_____ arboles:50 depth:4 ______
%:0.7894736842105263
%:0.7631578947368421
%:0.7631578947368421
_____ arboles:100 depth:4 ______
%:0.7894736842105263
%:0.7894736842105263
%:0.7763157894736842
_____ arboles:500 depth:4 ______
%:0.7894736842105263
%:0.7763157894736842
%:0.7763157894736842
_____ arboles:10 depth:10 ______
%:0.7894736842105263
%:0.75
%:0.7763157894736842
_____ arboles:50 depth:10 ______
%:0.7763157894736842
%:0.75
%:0.7763157894736842
_____ arboles:100 depth:10 ______
%:0.7894736842105263
%:0.8026315789473685
%:0.776315